version: 2.1

orbs:
  ci: kydeps/ci@dev:alpha

jobs:          
  build:
    executor: ci/kydeps
    working_directory: "~/src"
    steps:
      - checkout
      - run: mkdir ~/build
      - run: cmake -S ~/src -B ~/build
      - run: cmake --build ~/build
      - run: cd ~/build && ctest 

workflows:
  all:
    jobs:
      - build
